### ISSUE TITLE
Default bash completion for folder and files does not work

### ISSUE THREAD

**Issue by grumpyf0x48** [jonasbn/bash_completion_ack#3]
Without any bash completion script for ack, when you type ack then TAB the folder and files present in the current directory are proposed.

If you install the current ack Bash completion, it no longer works :-(

It is caused by the default Bash completion being disabled:

```
    # else
    #     compopt -o default
```

**Comment by jonasbn** [comment]
Thanks for the report @grumpyf0x48 I will have a look at it

**Comment by jonasbn** [comment]
Hi @grumpyf0x48 

I have changed the completion by removing the commented out code section. I hope it was not too much inconvenience to you. I had not spotted it myself, since I have changed to Zsh and I am mostly using `ag` for searching instead of `ack`.

Thanks again for the bug report, please let me know if you observe any other issues

**Comment by grumpyf0x48** [comment]
Thanks @jonasbn it works as expected.
